"use client"
import FormHeader from '@/components/backOffice/FormHeader';
import Arrayitemsinput from '@/components/Forminput/Arrayitemsinput';
import ImageInput from '@/components/Forminput/Imageinput';
import SelectInput from '@/components/Forminput/Selectinput';
import SubmitButton from '@/components/Forminput/SubmitButton';
import TextareaInput from '@/components/Forminput/TexrAreainput';
import TextInput from '@/components/Forminput/Textinput';
import { makePostRequest } from '@/lib/apiRequest';
import { generateSlug } from '@/lib/generateSlug';
import { Plus, X } from 'lucide-react';
import React, { useState } from 'react'
import { useForm } from 'react-hook-form';

export default function NewProduct() {

  const categories = [
    {
      id: 1,
      title: "Category 1",
    },
    {
      id: 2,
      title: "Category 2",
    },
    {
      id: 3,
      title: "Category 3",
    },
    {
      id: 4,
      title: "Category 4",
    },
    {
      id: 5,
      title: "Category 5",
    },
  ];
    const farmers = [
      {
        id: 1,
        title: "Farmer 1",
      },
      {
        id: 2,
        title: "Farmer 2",
      },
      {
        id: 3,
        title: "Farmer 3",
      },
      {
        id: 4,
        title: "Farmer 4",
      },
      {
        id: 5,
        title: "Farmer 5",
      },
    ];
// ------------Tags-------------

  const [imageUrl, setImageUrl] = useState("")
  const [loading, setLoading] = useState(false)
  const { register, reset, handleSubmit, formState: { errors } } = useForm()
      const [items, setItems] = useState([]);

  async function onSubmit(data) {
    
    const slug = generateSlug(data.title)
    data.slug = slug
    data.imageUrl = imageUrl
    data.tags =tags
    console.log(data)

    makePostRequest(setLoading, "api/products", data, "Product", reset); 

    setImageUrl("")

  }
  return (
    <div>
      <FormHeader title="New Product" />
      {/* -id(autogenerated), -title, -slug(autogenerated), -description, -image, sku, barcode, producrPrice, SalePrice, Category, Farmer, prodcutTag[]  */}

      <form
        onSubmit={handleSubmit(onSubmit)}
        className="w-full max-w-4xl p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700 mx-auto my-3 ">
        <div className="grid gap-4 sm:grid-cols-2 sm:gap-6">
          <TextInput
            label="Product Title"
            name="title"
            register={register}
            errors={errors}
          />
          <TextInput
            label="Product SKU"
            name="sku"
            register={register}
            errors={errors}
            className="w-full"
          />
          <TextInput
            label="Product Barcode"
            name="barcode"
            register={register}
            errors={errors}
            className="w-full"
          />
          <TextInput
            label="Product Price (Before Discount)"
            name="productPrice"
            type="number"
            register={register}
            errors={errors}
            className="w-full"
          />
          <TextInput
            label="Product Sale Price (Discounted)"
            name="salePrice"
            type="number"
            register={register}
            errors={errors}
            className="w-full"
          />
          <SelectInput
            label="Select Category"
            name="categoryId"
            register={register}
            errors={errors}
            className="w-full"
            options={categories}
          />
          <SelectInput
            label="Select Farmer"
            name="farmerId"
            register={register}
            errors={errors}
            className="w-full"
            options={farmers}
          />

          <ImageInput
            imageUrl={imageUrl}
            setImageUrl={setImageUrl}
            endpoint="productImageUploader"
            label="Product Image"
          />
          <TextareaInput
            label="Product Description"
            name="description"
            register={register}
            errors={errors}
          />
          {/* tags */}
          <Arrayitemsinput itemTitle="Tag" setItems={setItems} items={ items} />
        </div>
        <SubmitButton
          isLoading={loading}
          buttonTitle="Create Product"
          loadingButtonTitle="Creating Product please wait ..."
        />
      </form>
    </div>
  );
}
