import { NextResponse } from "next/server";

export async function POST(request) {
    try {
              {
                /* -id(autogenerated), -title, -slug(autogenerated),
                 -description, -image, sku, barcode,
                  producrPrice, SalePrice, Category,
                   Farmer, prodcutTag[]  */
              }

        const productData = await request.json()
        
        console.log(productData);
        return NextResponse.json(productData);
    } catch (error) {
        console.log(error)
        return NextResponse.json(
          {
            message: "Failed to create product",
            error,
          },
          { status: 500 }
        );
    }
}